### ISSUE TITLE
adjust location of tweet

### ISSUE THREAD

**Issue by rbracket** [pdxosgeo/workzonepdx#2]
The story behind this issue is this:

A tweet, with or without a photo, with or without lat/long in the exif data may be located at the wrong location.  

This happens when the tweet is submitted from a location that is not the closure location.

**Comment by twelch** [comment]
@rbracket  I think the Twitter app simply asks your browser/phone what its location is.  If you're at home on your laptop then it will pick up your home location using your IP address.  That's been my experience.

**Comment by twelch** [comment]
I also haven't found a way to edit your location after tweeting, only deleting and readding.  I think you have to have 'precise location' turned on in the Twitter app to get an accurate read.

**Comment by twelch** [comment]
Putting workflow in place for replying to poster if needed to fix, or fixing in the Google sheet after the fact.   Completing for now
