### ISSUE TITLE
Delete master branch

### ISSUE THREAD

**Issue by ngoldman** [pdxosgeo/workzonepdx#26]
Hi @twelch! I recommend you switch the main branch of the repo to point to `gh-pages` then delete `master` since it's a duplicate branch. That way first-timers will immediately see the main branch when they visit the repository, pull requests will automatically point to the `gh-pages` branch, and there will be no unnecessary confusion.

![screen shot 2016-03-04 at 10 35 34 am](https://cloud.githubusercontent.com/assets/427322/13536467/e276d2d4-e1f4-11e5-828c-1aa0c805e4b2.png)

**Comment by twelch** [comment]
Thanks for the thoughts @ngoldman.  I was thinking that gh-pages being basically an auto-deployed production branch that it shouldn't receive PRs directly, rather they should trickle up to master and when ready merged over to gh-pages.

**Comment by ngoldman** [comment]
Fair enough.
